export const IMAGE_PICK_REQUEST = 'IMAGE_PICK_REQUEST';
export const IMAGE_PICK_SUCCESS = 'IMAGE_PICK_SUCCESS';
export const IMAGE_PICK_FAILURE = 'IMAGE_PICK_FAILURE';

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
