export const FIREBASE_UPDATE_REQUESTED = 'FIREBASE_UPDATE_REQUESTED';
export const FIREBASE_UPDATE_FULFILLED = 'FIREBASE_UPDATE_FULFILLED';
export const FIREBASE_UPDATE_REJECTED = 'FIREBASE_UPDATE_REJECTED';

export const FIREBASE_REMOVE_REQUESTED = 'FIREBASE_REMOVE_REQUESTED';
export const FIREBASE_REMOVE_FULFILLED = 'FIREBASE_REMOVE_FULFILLED';
export const FIREBASE_REMOVE_REJECTED = 'FIREBASE_REMOVE_REJECTED';

export const FIREBASE_LISTEN_REQUESTED = 'FIREBASE_LISTEN_REQUESTED';
export const FIREBASE_LISTEN_FULFILLED = 'FIREBASE_LISTEN_FULFILLED';
export const FIREBASE_LISTEN_REJECTED = 'FIREBASE_LISTEN_REJECTED';
export const FIREBASE_LISTEN_CHILD_ADDED = 'FIREBASE_LISTEN_CHILD_ADDED';
export const FIREBASE_LISTEN_CHILD_CHANGED = 'FIREBASE_LISTEN_CHILD_CHANGED';
export const FIREBASE_LISTEN_CHILD_REMOVED = 'FIREBASE_LISTEN_CHILD_REMOVED';
export const FIREBASE_LISTEN_REMOVED = 'FIREBASE_LISTEN_REMOVED';

export const FIREBASE_REMOVE_LISTENER_REQUESTED =
  'FIREBASE_REMOVE_LISTENER_REQUESTED';
export const FIREBASE_REMOVE_ALL_LISTENERS_REQUESTED =
  'FIREBASE_REMOVE_ALL_LISTENERS_REQUESTED';
