export const FIREBASE_UPDATE_REQUEST = 'FIREBASE_UPDATE_REQUEST';
export const FIREBASE_UPDATE_SUCCESS = 'FIREBASE_UPDATE_SUCCESS';
export const FIREBASE_UPDATE_FAILURE = 'FIREBASE_UPDATE_FAILURE';

export const FIREBASE_REMOVE_REQUEST = 'FIREBASE_REMOVE_REQUEST';
export const FIREBASE_REMOVE_SUCCESS = 'FIREBASE_REMOVE_SUCCESS';
export const FIREBASE_REMOVE_FAILURE = 'FIREBASE_REMOVE_FAILURE';

export const FIREBASE_LISTEN_REQUEST = 'FIREBASE_LISTEN_REQUEST';
export const FIREBASE_LISTEN_SUCCESS = 'FIREBASE_LISTEN_SUCCESS';
export const FIREBASE_LISTEN_FAILURE = 'FIREBASE_LISTEN_FAILURE';
export const FIREBASE_LISTEN_CHILD_ADDED = 'FIREBASE_LISTEN_CHILD_ADDED';
export const FIREBASE_LISTEN_CHILD_CHANGED = 'FIREBASE_LISTEN_CHILD_CHANGED';
export const FIREBASE_LISTEN_CHILD_REMOVED = 'FIREBASE_LISTEN_CHILD_REMOVED';
export const FIREBASE_LISTEN_REMOVED = 'FIREBASE_LISTEN_REMOVED';

export const FIREBASE_REMOVE_LISTENER_REQUEST =
  'FIREBASE_REMOVE_LISTENER_REQUEST';
export const FIREBASE_REMOVE_ALL_LISTENERS_REQUEST =
  'FIREBASE_REMOVE_ALL_LISTENERS_REQUEST';
