export const FIREBASE_REMOVE_REQUESTED = 'FIREBASE_REMOVE_REQUESTED';
export const FIREBASE_REMOVE_FULFILLED = 'FIREBASE_REMOVE_FULFILLED';
export const FIREBASE_REMOVE_REJECTED = 'FIREBASE_REMOVE_REJECTED';
