export const FIREBASE_UPDATE_REQUESTED = 'FIREBASE_UPDATE_REQUESTED';
export const FIREBASE_UPDATE_FULFILLED = 'FIREBASE_UPDATE_FULFILLED';
export const FIREBASE_UPDATE_REJECTED = 'FIREBASE_UPDATE_REJECTED';
